        <div dojoType="dojox.data.QueryReadStore" jsId="testStore" url="/index/autocomplete"></div>
        <div id="loginwrapper">
            <div id="logincontent">
                <?php if($this->errorMessage != ""): ?>
                <p class="errors"><?= $this->errorMessage; ?></p>
                <?php endif; ?>

                <?= $this->loginForm; ?>
                <?= $this->DojoForm; ?>
            </div>
        </div>