<?php $this->dojo()->enable(); ?>
<div id="wrapper">
    <div id="headerContainer">
        <img id="logo" src="/files/images/logo.png" />
        <div id="calNavigationContainer">
            <h1>
                <?php
                    if($this->isArchived == true){
                        print 'Diese Woche ist deaktiviert!';
                    }else{
                        print "&nbsp;";
                    }
                ?>
            </h1>
            <form id="kw-form" name="kw-form">
                KW wählen: <select name="kw" id="kw" onChange="jumpMenue( this.form )">
                    <?php
                        for ($i=($this->shownCalendarWeek-6);$i<=($this->shownCalendarWeek+10);$i++){

                            if($i == $this->thisCalendarWeek){
                                $thisWeekDesc = "Aktuell: ";
                            }else{
                                $thisWeekDesc = "";
                            }

                            if($i == $this->shownCalendarWeek){
                                echo '<option value="' . $this->url(array('controller'=>'admincal','action'=>'showcal', 'week'=>$i)) . '" selected="selected" />' . $thisWeekDesc . $i . '</option>';
                            }else{
                                echo '<option value="' . $this->url(array('controller'=>'admincal','action'=>'showcal', 'week'=>$i)) . '" />' . $thisWeekDesc . $i . '</option>';
                            }
                        }
                    ?>
                </select>
            </form>
            <ul id="calNavigation">
                <?php
                    if($this->isArchived == false){
                        echo '<li><a href="' . $this->url(array('controller'=>'admincal','action'=>'archive', 'dayOfThisWeek'=>$this->dayOfThisWeek)) . '" title="Supis können keine &Auml;derungen mehr vornehmen"><img src="/files/images/save.png" />Woche deaktivieren</a></li>';
                    }else{
                        echo '<li><a href="' . $this->url(array('controller'=>'admincal','action'=>'unarchive', 'dayOfThisWeek'=>$this->dayOfThisWeek)) . '" title="Supis können wieder &Auml;derungen vornehmen"><img src="/files/images/save.png" />Woche aktivieren</a></li>';
                    }
                ?>
                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'logout'));?>" title="Abmelden"><img src="/files/images/logout.png" />Abmelden</a></li>
            </ul>
        </div>
    </div>
    <table id="calTable">
        <tr>
            <th>Zeit</th>
            <?php
                $i = 0;
                foreach ($this->openDays as $key => $val):
            ?>
            <th>
                <?php
                    echo date("l d.m.Y", $this->escape($val));
                ?>
            </th>
            <?php
                $i++;
                endforeach;
            ?>
        </tr>
        <?php for($a=$this->minOpenHours;$a<=$this->maxOpenHours;$a++) :?>
        <tr>
            <td class="time"><?= $this->escape($this->openHours[$a]); ?></td>
            <?php for($i=0;$i<count($this->openDays);$i++):
            if($this->openCloseMatrix[$i][$a] == 1) {
                if($this->bookedMatrix[$i][$a] != "nicht gebucht") {
                    echo '<td class="calentry selected">';
                    foreach($this->bookedMatrix[$i][$a] as $username){
                        echo $username . "<br/>";
                    }
                    echo '</td>';
                } else {
                    echo '<td class="calentry notselected">
                            &nbsp;
                          </td>';
                }
            } else {
                print '<td class="calentry closed">geschlossen</td>';
            }
            endfor; ?>
        </tr>
        <?php endfor; ?>
    </table>
</div>